bowling_homepage:
    path:     /
    defaults: { _controller: BowlingBundle:Game:index }

start_game:
    path: /start
    defaults: { _controller: BowlingBundle:Game:start }
    methods: ['POST']

game_page:
    path: /game
    defaults: { _controller: BowlingBundle:Game:play }
    methods: ['GET']

throw_ball:
    path: /throw_ball
    defaults: { _controller: BowlingBundle:Game:throwBall }
    methods: ['POST']