services:
    service.lane:
        class: ApiBundle\Service\LaneService
        arguments: ["@doctrine"]

    service.game:
        class: ApiBundle\Service\GameService
        arguments: ["@doctrine", "@session"]

    service.frame:
        class: ApiBundle\Service\FrameService
        arguments: ["@doctrine", "@session"]