<?php

namespace ApiBundle\Repository;

/**
 * BallRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BallRepository extends \Doctrine\ORM\EntityRepository
{
}
