<?php

namespace ApiBundle\Repository;

/**
 * FrameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FrameRepository extends \Doctrine\ORM\EntityRepository
{
}
