<?php

namespace ApiBundle\Repository;

/**
 * LaneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LaneRepository extends \Doctrine\ORM\EntityRepository
{
}
